export const COOKIES = Symbol('cookies');
export const MAX_COOKIE_SIZE = 4096;
export const REASSIGN = Symbol('reassign');
export const REGENERATED_SESSION_ID = Symbol('regenerated_session_id');
export const SESSION = Symbol('session');
export const SESSION_ID = Symbol('session_id');
export const SESSION_STORE = Symbol('session store');
export const SET_SESSION_COOKIE = Symbol('set cookies');
export const SKIP_SILENT_LOGIN_COOKIE_NAME = 'skipSilentLogin';
